apiVersion: v1
kind: Pod
metadata:
  labels:
    app: probe-liveness
  name: probe-liveness
spec:
  containers:
    - name: probe-liveness
      image: busybox
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 6000
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5